services:
  app:
    container_name: mx-server
    image: blxcwg666/mx-server:latest
    environment:
      - TZ=Asia/Shanghai
      - NODE_ENV=production
      - DB_HOST=mongo
      - REDIS_HOST=redis
      - MEILI_HOST=meilisearch
      - MEILI_MASTER_KEY=YOUR_SUPER_SECURED_MEILI_MASTER_KEY
      - ALLOWED_ORIGINS=localhost
      - JWT_SECRET=YOUR_SUPER_SECURED_JWT_SECRET_STRING
    volumes:
      - ./data/mx-space:/root/.mx-space
    ports:
      - '2333:2333'
    depends_on:
      - mongo
      - redis
      - meilisearch
    networks:
      - mx-space
    restart: unless-stopped
    healthcheck:
      test: [CMD, curl, -f, 'http://127.0.0.1:2333/api/v2/ping']
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  mongo:
    container_name: mongo
    image: mongo:7
    volumes:
      - ./data/db:/data/db
    networks:
      - mx-space
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: [CMD-SHELL, 'redis-cli ping | grep PONG']
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    networks:
      - mx-space
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:v1.12
    container_name: meilisearch
    environment:
      - MEILI_ENV=production
      - MEILI_MASTER_KEY=YOUR_SUPER_SECURED_MEILI_MASTER_KEY
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./data/meili:/meili_data
    healthcheck:
      test: [CMD, curl, -f, 'http://127.0.0.1:7700/health']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    networks:
      - mx-space
    restart: unless-stopped

networks:
  mx-space:
    driver: bridge
